#!/bin/sh

# build.sh creates or fetches your base image. This is just a placeholder.
# You can create your own default build.sh by creating ~/.flakes/package/build.sh
# Delete or comment out this line after you set up your buildscript
echo "Please setup src/build.sh before building your package" 1>&2; exit 1

# You can create/fetch you container however you want, the only condition is
# that its tag must be equal to the contents of $1

# Build a container from a Dockerfile using buildah
# buildah build -f src/Dockerfile -t $1 .
