[package]
name = "flakes"
version = "0.1.0"
edition = "2021"
crate-type = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.185", features = ["derive"]}
serde_json = {version = "1.0.105", optional = true}
thiserror = "1.0.47"

[features]
json = ["serde_json"]
