on:
  push:
    branches:
      - "master"
  pull_request:

name: Robot Full Test
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install python3-docutils
      - name: Build Flake
        run:  make build
      - name: Install Flake
        run:  sudo make install
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0